### PR TITLE
Add feedback form in docs; Fix homepage style; 

### PR DESCRIPTION
**Pull request by ghost**
1. Changed CSS for header and logo svg.
2. Added a guideline illustrating the workflow about how to contribute to this project through a pull request.
Including the details about how to contribute to the translated docs, versioned docs in readme file.

## Check List
- [x] The current home page is not responsive to mobile device:
- [x] Please add a guideline illustrating the workflow about how to contribute to this project through a pull request.
Including the details about how to contribute to the translated docs, versioned docs, etc

### CODE REVIEW

**Comment by ghost** [comment]
### Check List

- [x]  Add a feedback section on footer
- [x]  update *Edit this page* button

**Comment by ghost** [comment]
### **CheckList**

- [x]  jumping to GitHub to subject an issue (with the doc file automatically linked).
- [x] Can provide useful external links to the users.

**Comment by yingjunwu** [comment]
You may want to change the PR title. Please remember that the PR title should be short yet informative.

**Review by cloudcarver — APPROVED** [review]
LGTM

**Comment by cloudcarver** [comment]
Thanks for your good work. The PR title should summarize the main idea of the merged code, and adding a label will be helpful for maintaining the repo.

**Comment by cloudcarver** [comment]
Closes #13
Closes #12

**Pull request merged**
