### PR TITLE
feat: add LinkedIn Icon

### PR DESCRIPTION
**Pull request by TingJianZheng**
feat: add LinkedIn Icon

### CODE REVIEW

**Review by cloudcarver — APPROVED** [review]
LGTM!

**Comment by CharlieSYH** [comment]
Thanks @TingJianZheng for taking care of this.

Seems that we still have some ratio issues to be solved before merging this PR:
Some icons are more narrow than they should be. I think it has something to do with the ratio settings (height/width).
Portrait (mobile):
image
Landscape (wide-screen):
image

And the icons are not perfectly aligned with the back-to-top button:
image

**Comment by TingJianZheng** [comment]
> Thanks @TingJianZheng for taking care of this.
> 
> Seems that we still have some ratio issues to be solved before merging this PR: Some icons are more narrow than they should be. I think it has something to do with the ratio settings (height/width). Portrait (mobile): image Landscape (wide-screen): image
> 
> And the icons are not perfectly aligned with the back-to-top button: image

I think it's the padding, I changed the way the icon is centered

**Comment by CharlieSYH** [comment]
Big thanks! Perfect now.

**Review by CharlieSYH — APPROVED** [review]

**Pull request merged**
