### PR TITLE
Document internal tables

### PR DESCRIPTION
**Pull request by hengm3467**
## Info
- **Description**: 
Create the reference information about `SHOW INTERNAL TABLES`. Added a bit introduction to internal tables and internal states. 

Later on, we may need to have a how-to guide about how to use internal tables for performance tuning or other possible scenarios. This will be done after we have the new articles ready by Tenny, and will be included in a separate PR.

- **Preview**: 
[ Paste the preview link to the edited page here. ]

- **Related code PR**: 
[ Provide the link to the code PR here. For example, https://github.com/risingwavelabs/risingwave/pull/4085. Delete this part if there's no code PR related. ]

- **Related doc issue**: 
Resolves [ Provide the link to the doc issue here. ]

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: image
</details>

### CODE REVIEW

**Review by neverchanje — APPROVED** [review]

**Review by chenzl25 — APPROVED** [review]

**Comment by TennyZhuang** [comment]
Should we document the feature? I guess we may change it frequently, at least we should mark it as an experimental feature.

**Comment by TennyZhuang** [comment]
We've already added `__` prefix to the internal tables, generally we don't want any users to depend on this feature now.

**Comment by st1page** [comment]
Maybe we can add some warning in the doc that we might change the internal table's schema, content, and naming rule of the internal table.

**Comment by hengm3467** [comment]
@TennyZhuang @st1page I can revert this PR if we are not ready to announce it, though I don't think people know how to use this feature without a proper how-to guide.

**Pull request merged**
