### PR TITLE
Add bytebase to integration page

### LINKED ISSUE #1725: document bytebase support
### Related code PR

https://github.com/risingwavelabs/risingwave/issues/10964

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.bytebase.com/docs/introduction/supported-databases/
Bytebase has listed RisingWave as a supported database. Hence, we should mark it as an established integration in https://docs.risingwave.com/docs/current/rw-integration-summary/ as well.

### Reference

_No response_

### PR DESCRIPTION
**Pull request by emile-00**
## Info

- **Description**

  - Add bytebase to integration page under BI and data analytic platforms section

- **Notes**

  - [ Include any supplementary context or references here. ]

- **Related code PR**

  - https://github.com/risingwavelabs/risingwave/issues/10964

- **Related doc issue**
  
  Resolves https://github.com/risingwavelabs/risingwave-docs/issues/1725

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Review by WanYixian — APPROVED** [review]

**Review by ShanlanLi — APPROVED** [review]
LGTM

**Comment by neverchanje** [comment]
I suggest adding a link https://www.bytebase.com/docs/introduction/supported-databases/ bytebase's document on "Available".

**Review by neverchanje — APPROVED** [review]
Rest LGTM

**Review by hengm3467 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
