### PR TITLE
Updating CREATE INDEX - adding the INCLUDE clause

### LINKED ISSUE #213: Update CREATE INDEX
### Related code PR

https://github.com/singularity-data/risingwave/pull/4340/files

### Which part(s) of the docs might be affected or should be updated? And how?

Update https://github.com/singularity-data/risingwave-docs/blob/main/temp/sql-create-index.md (syntax and examples). 

CREATE INDEX is not shown to users because: 
image
So keep the file in the temp folder.
Skip Release Notes.

### Reference

https://www.postgresql.org/docs/14/sql-createindex.html

### PR DESCRIPTION
**Pull request by CharlieSYH**
## Info
- **Description**: 
Adding the INCLUDE clause to CREATE INDEX.

- **Related code PR**: 
https://github.com/singularity-data/risingwave/pull/4340

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/213

- **Notes**: 
CREATE INDEX is still not visible to users. It's in the temp folder which is not included in the publishing process. Let me know if it's ready.

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview and the updated parts look all good. <details><summary>How?</summary>image</details>
  - [ ] (For version-specific PR) I have confirmed that this PR is for a released version. If the software version is not released, put it on hold.

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

### CODE REVIEW

**Comment by chenzl25** [comment]
FYI, index selection for batch query is ready, so users can create an index working like OLTP databases.

**Review by chenzl25 — APPROVED** [review]
LGTM

**Comment by CharlieSYH** [comment]
> FYI, index selection for batch query is ready, so users can create an index working like OLTP databases.

Noted. Thanks, @chenzl25 .

**Review by hengm3467 — APPROVED** [review]
Looks good to me.

**Pull request merged**
