### PR TITLE
add zh docs for real-time-ad-performance-analysis

### PR DESCRIPTION
**Pull request by thexiay**
## Info

- **Description**

  - [ What's changed? Which parts of the docs are affected? ]

- **Notes**

  - [ Include any supplementary context or references here. ]

- **Related code PR**

  - [ Provide a link to the relevant code PR here, if applicable. ]

- **Related doc issue**
  
  Resolves [ Provide a link to the relevant doc issue here, if applicable. ]

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Comment by CharlieSYH** [comment]
@thexiay Please close this PR and translate the file in this repo: https://github.com/risingwavelabs/risingwave-docs-zh

**Comment by CAJan93** [comment]
English, please 😓

**Comment by CharlieSYH** [comment]
> English, please 😓

@CAJan93 Haha, @thexiay is translating our demos from EN to ZH. But this PR was submitted to the wrong repo.

**Comment by CAJan93** [comment]
> @CAJan93 Haha, @thexiay is translating our demos from EN to ZH. But this PR was submitted to the wrong repo

No worries. Like I would be interested in this demo and trying this myself, but I have zero ZH skills hahah

**Pull request closed without merging**
