### PR TITLE
refactor: change link for edit button to the real edit page

### PR DESCRIPTION
**Pull request by Sunt-ing**
IMO usually edit link should be linked to the edit page. Not sure about this.

### CODE REVIEW

**Comment by cloudcarver** [comment]
cc. @CharlieSYH

**Comment by Sunt-ing** [comment]
We find that some open-source projects choose to remain this way: "\*/blob/\*". Some we decide to use this way also. Example: https://github.com/apache/shardingsphere/edit/master/docs/document/content/overview/_index.en.md

**Comment by Sunt-ing** [comment]
We find that some open-source projects choose to remain this way: "*/blob/*". Some we decide to use this way also.

**Review by CharlieSYH — APPROVED** [review]
To conclude, the "Edit this page" button still goes to the 'blob' not 'edit' page because it's easier to preview the file content.

**Pull request merged**
