### PR TITLE
Update Get-Started.md

### PR DESCRIPTION
**Pull request by CharlieSYH**
@TennyZhuang @fuyufjh 
Please check if the naming rule for properties has changed from "kafka.brokers" to "kafka_brokers". If not, is there any issue or PR that I can track?

### CODE REVIEW

**Comment by TennyZhuang** [comment]
Hi, I'm still thinking about what's a better naming since I met some special cases that `under_score` may not work well. I will take over to update the doc as well as the codes.

**Review by huangjw806 — APPROVED** [review]
LGTM!

**Comment by TennyZhuang** [comment]
Please revert the PR, we've not done the renaming -(

**Comment by CharlieSYH** [comment]
No need to revert. This PR does not include changes to the property names. I was just tagging you to be sure we have not changed the naming rules.

On Aug 1, 2022, at 16:16, @TennyZhuang >> wrote:
Please revert the PR, we've not done the renaming -(

**Pull request merged**
