### PR TITLE
Remove etcd option in metadata backend

### LINKED ISSUE #2493: Change required: use Postgres as the metadata backend instead of etcd
### Related code PR

_No response_

### Which part(s) of the docs might be affected or should be updated? And how?

Right now, in all the "Deploy ..." pages, they still choose `etcd` as the metadata backend.

SCR-20240821-m4f

Starting from the next release `2.0`, RW will use Postgres by default. It has been tested for a few versions right now. The stability is good.

### Reference

_No response_

### PR DESCRIPTION
**Pull request by WanYixian**
## Description

Remove etcd option in metadata backend in 2.0

## Related doc issue

Resolve #2493

## Checklist

- [ ] I have checked the doc site preview, and the updated parts look good.
- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`emile-00`, `hengm3467`, & `WanYixian`).

### CODE REVIEW

**Review by lmatz — APPROVED** [review]
LGTM!

BTW, 

SCR-20240822-ksc
mentioned `etcd` too

**Comment by WanYixian** [comment]
Hi @arkbriar, deploy on K8S with Helm also mentioned ETCD: https://docs.risingwave.com/docs/next/risingwave-k8s-helm/. 
As discussed, please help update [bundled](https://github.com/risingwavelabs/helm-charts/blob/main/docs/CONFIGURATION.md#bundled-etcdminio-as-stores) part in config file when you have time, thanks!
image

**Review by ShanlanLi — APPROVED** [review]
LGTM

**Comment by WanYixian** [comment]
> LGTM!
> 
> BTW,
> 
> SCR-20240822-ksc mentioned `etcd` too

Removed now, will merge this PR if no questions

**Pull request merged**
