### PR TITLE
Doc the DEFAULT clause in CREATE TABLE

### LINKED ISSUE #1336: Default values in create table
Example

```sql
create table t1 (v1 int, v2 int default 2+3);

insert into t1 values (0, 0);
```

See more https://github.com/risingwavelabs/risingwave/pull/9521

### PR DESCRIPTION
**Pull request by CharlieSYH**
## Info

- **Related code PR**

  https://github.com/risingwavelabs/risingwave/pull/9521

- **Related doc issue**
  
  Resolves https://github.com/risingwavelabs/risingwave-docs/issues/1336

## For reviewers

- **Preview**

  https://pr-1370.d2fbku9n2b6wde.amplifyapp.com/docs/dev/sql-create-table/#parameters

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Review by BugenZhao — APPROVED** [review]
LGTM. Would you please also document the `DEFAULT` clause in `ADD COLUMN`?

**Comment by CharlieSYH** [comment]
> LGTM. Would you please also document the `DEFAULT` clause in `ADD COLUMN`?

@BugenZhao Is this the correct PR? https://github.com/risingwavelabs/risingwave/pull/12678

**Comment by BugenZhao** [comment]
> > LGTM. Would you please also document the `DEFAULT` clause in `ADD COLUMN`?
> 
> @BugenZhao Is this the correct PR? [risingwavelabs/risingwave#12678](https://github.com/risingwavelabs/risingwave/pull/12678)

Yeah, partially. Also https://github.com/risingwavelabs/risingwave/pull/9762. 

Descriptions that might be helpful for you:

Users can write `DEFAULT xxx` clause when `ALTER TABLE ADD COLUMN`. Historical data will be filled (actually not, it's just like a "view") with the default value provided here. Future inserts with this column absent will also use this default value as usual.

If the default expression is impure, such as `NOW()`, all the values for historical data will be filled with the result evaluated at the time of `ADD COLUMN`. Future inserts will evaluate in-place.

**Review by BugenZhao — APPROVED** [review]
LGTM

**Review by hengm3467 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
