### PR TITLE
Update Setup section and include Homebrew

### LINKED ISSUE #932: Document the Homebrew one-liner installation: `brew install risingwave`
### Related code PR

https://github.com/risingwavelabs/risingwave/issues/9884

### Which part(s) of the docs might be affected or should be updated? And how?

Steup

### Reference

_No response_

### PR DESCRIPTION
**Pull request by CharlieSYH**
## Info

- **Preview**: 
https://pr-948.d2fbku9n2b6wde.amplifyapp.com/docs/upcoming/get-started/

- Reorganize setup section
image

- Revamp Get started and put essential content (setup, source, sql, sink) into a Quickstart guide.
- Add Homebrew installation method
- Update related topics and links

**Do not merge this PR.**

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: image
</details>

### CODE REVIEW

**Review by BugenZhao — COMMENTED** [review]
LGTM

**Comment by hengm3467** [comment]
Looks good, but the "quick" start is still not that quick. Let's keep Homebrew and leave out all other options to somewhere else. I'm working on this now.

**Comment by CharlieSYH** [comment]
> Looks good, but the "quick" start is still not that quick. Let's keep Homebrew and leave out all other options to somewhere else. I'm working on this now.

Made some updates. @hengm3467 Please check out https://pr-948.d2fbku9n2b6wde.amplifyapp.com/docs/upcoming/get-started/

**Review by hengm3467 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
