### PR TITLE
update create source syntax

### PR DESCRIPTION
**Pull request by tabVersion**
## Info

- **Description**

  [ What's changed? Which parts of the docs are affected? ]

related: https://github.com/risingwavelabs/rfcs/pull/64

This release will only contain part of the proposal. 

* separate `format` and `encode`
* move parser related properties to encode properties

- **Notes**

  [ Include any supplementary context or references here. ]

- **Related code PR**

  https://github.com/risingwavelabs/risingwave/pull/10768
  https://github.com/risingwavelabs/risingwave/pull/10868

- **Related doc issue**
  
  Resolves [ Provide a link to the relevant doc issue here, if applicable. ]

## For reviewers

- **Preview**

  [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **upcoming** version of the documentation. ]

- **Key points**

  [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Comment by neverchanje** [comment]
Thanks Bohan. I didn't find where in the new doc had our BYTES format been documented. Please ensure that we have included BYTES as well.

**Comment by CharlieSYH** [comment]
It's not included in v1.0.0. Correct?
It seems that these two PRs are merged after the release of v1.0.0. See https://github.com/risingwavelabs/risingwave/compare/v1.0.0...main
If not, we should not merge this PR for now.

**Comment by st1page** [comment]
> It's not included in v1.0.0. Correct?
It seems that these two PRs are merged after the release of v1.0.0. See https://github.com/risingwavelabs/risingwave/compare/v1.0.0...main
If not, we should not merge this PR for now.

They have been included in v1.0. The 
- https://github.com/risingwavelabs/risingwave/pull/10856 is the cherry-pick
- https://github.com/risingwavelabs/risingwave/pull/10868 is merged into branch of v1.0 directly

**Review by CharlieSYH — APPROVED** [review]
LGTM

**Pull request merged**
