### PR TITLE
update: modified the redirection rules on documentation

### LINKED ISSUE #1226: Website: URL redirect rule changes
### Related code PR

_No response_

### Which part(s) of the docs might be affected or should be updated? And how?

Expected rule changes:

/dev_version -> /dev (before: /dev_version -> /current)
/docs/page1 -> /docs/current/page1 (before: /docs/page1 -> /docs/current/intro)

### Reference

_No response_

### PR DESCRIPTION
**Pull request by TingJianZheng**
/xxx/get-started/ -> /current/get-started/
If the version number in the URL is removed, then redirect to the page corresponding to version "current," and it's necessary to verify if the page exists.
## Info

- **Description**

  [ What's changed? Which parts of the docs are affected? ]

- **Notes**

  [ Include any supplementary context or references here. ]

- **Related code PR**

  [ Provide a link to the relevant code PR here, if applicable. ]

- **Related doc issue**
  
  Resolves [ Provide a link to the relevant doc issue here, if applicable. ]

## For reviewers

- **Preview**

  [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **upcoming** version of the documentation. ]

- **Key points**

  [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Comment by CharlieSYH** [comment]
Thanks, @TingJianZheng. There's one other request regarding the URL redirecting rule change:

/dev_version -> /dev (before: /dev_version -> /current) . 
For example, 1.2 is the current dev version, and when I visit `/docs/1.2/use-cases`, it should redirect to `/docs/dev/use-cases`, but now it redirects to `/docs/current/use-cases`. For future releases, we (the doc team) can update the rule according to the latest dev version number.

This PR resolves https://github.com/risingwavelabs/risingwave-docs/issues/1226

**Comment by TingJianZheng** [comment]
> 

The new redirection rules have been added.

**Review by chrispaul-03 — APPROVED** [review]
LGTM!

**Review by CharlieSYH — APPROVED** [review]
Thanks!!

**Pull request merged**
