### PR TITLE
remove usage of kafka.brokers  and kafka.topic

### PR DESCRIPTION
**Pull request by xxchan**
## Info
- **Description**: 
[ What's changed? ]

This should be changed since 0.1.12. ref: [release note](https://github.com/risingwavelabs/risingwave-docs/blob/d0373a393f31c74dd6025015bf0c37e651036962/docs/release-notes.md#connectors-5)

`properties.bootstrap.server` is documented in connector parameters: https://www.risingwave.dev/docs/current/create-source-kafka/#connector-parameters But `kafka.brokers` is used in examples.

P.S. I found this when playing RW cloud demo (see https://www.notion.so/risingwave-labs/kafka-brokers-and-kafka-topic-is-not-supported-52aed6a7f313415d8b519bef0310ccc8?pvs=4), where I find it doesn't support `kafka.brokers`. But latest RW supports it.

- **Preview**: 
[ Paste the preview link to the edited page here. ]

- **Related code PR**: 
[ Provide the link to the code PR here. For example, https://github.com/risingwavelabs/risingwave/pull/4085. Delete this part if there's no code PR related. ]

- **Related doc issue**: 
Resolves [ Provide the link to the doc issue here. ]

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: image
</details>

### CODE REVIEW

**Review by xx01cyx — APPROVED** [review]
LGTM. BTW, shall we maintain backward capability by still keeping the old configurations in our code?

**Comment by xxchan** [comment]
> LGTM. BTW, shall we maintain backward capability by still keeping the old configurations in our code?

cc @tabVersion 

BTW Currently they are kept in main. But it seems 0.1.17 doesn’t have them..

**Comment by xxchan** [comment]
https://risingwave-community.slack.com/archives/C03BW71523T/p1679907195103219
user reported this issue

**Review by hengm3467 — APPROVED** [review]
LGTM. Thanks a lot! @xxchan

**Pull request merged**
