### PR TITLE
Add metadata options for PG, MySQL and MongoDB

### LINKED ISSUE #2234: Document: feat(cdc): support more metadata columns for MySQL, PG and MongoDB
This issue tracks the documentation update needed for the merged PR #17051.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17051
Source PR Merged At: 2024-06-05T09:37:28Z

### PR DESCRIPTION
**Pull request by WanYixian**
## Info

- **Description**

  - Add metadata options for PG, MySQL and MongoDB

- **Related code PR**

  - https://github.com/risingwavelabs/risingwave/pull/17051

- **Related doc issue**
  
  Resolves https://github.com/risingwavelabs/risingwave-docs/issues/2234

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`emile-00`, `hengm3467`, & `WanYixian`).

### CODE REVIEW

**Comment by WanYixian** [comment]
@hzxa21  I used the example listed in [code PR ](https://github.com/risingwavelabs/risingwave/pull/17051)for PG and MySQL, please help provide an example of MongoDB, thanks!

**Review by hzxa21 — APPROVED** [review]
LGTM. Thanks for the PR!

**Review by ShanlanLi — APPROVED** [review]
LGTM

**Comment by hzxa21** [comment]
> @hzxa21 I used the example listed in [code PR ](https://github.com/risingwavelabs/risingwave/pull/17051)for PG and MySQL, please help provide an example of MongoDB, thanks!

You can see here for an example for Mongo:
https://github.com/risingwavelabs/risingwave/blob/5f09a750bbb3592b810ac6b92ba08d065105f2ef/e2e_test/source/cdc/mongodb/mongodb_basic.slt#L5
```
CREATE TABLE users (_id JSONB PRIMARY KEY, payload JSONB)
INCLUDE TIMESTAMP as commit_ts
INCLUDE DATABASE_NAME as database_name
INCLUDE COLLECTION_NAME as collection_name
WITH (
  connector = 'mongodb-cdc',
  mongodb.url = 'mongodb://mongodb:27017/?replicaSet=rs0',
  collection.name = 'random_data.*'
);
```

**Pull request merged**
