### PR TITLE
Add diagram for SHOW FUNCTIONS

### PR DESCRIPTION
**Pull request by bernscode**
Add diagram for SHOW FUNCTIONS.

## Info
- **Description**: 
Add diagram for SHOW FUNCTIONS.

- **Preview**: 
https://pr-858.d2fbku9n2b6wde.amplifyapp.com/docs/upcoming/sql-show-functions/

- **Related code PR**: 
N/A

- **Related doc issue**: 
Resolves no doc issue.

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: image
</details>

### CODE REVIEW

**Review by CharlieSYH — APPROVED** [review]
Made a slight change to the code block.

**Comment by hengm3467** [comment]
@bernscode Let's have a Syntax section above the Examples section. The diagram should be in the Syntax section. Thanks.

**Comment by bernscode** [comment]
@hengm3467 Good point! I've made the update on the latest commit. Thanks!

**Comment by hengm3467** [comment]
Somehow I don't see the diagram using the preview link. Not sure if this is just me.

**Comment by CharlieSYH** [comment]
> Somehow I don't see the diagram using the preview link. Not sure if this is just me.

@hengm3467 I can see the diagram
image

**Review by hengm3467 — APPROVED** [review]

**Pull request merged**
