### PR TITLE
add current_setting function

### LINKED ISSUE #1036: Document current_setting()
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10269

### Which part(s) of the docs might be affected or should be updated? And how?

Add a new page: System Administration Functions and document this function.

### Reference

https://www.postgresql.org/docs/current/functions-admin.html

### PR DESCRIPTION
**Pull request by hengm3467**
## Info

- **Description**

Add the system administration function current_setting(), and add several supported settings. Some settings don't have values yet, like `datestyle`, which I didn't include. I'm not sure if we are ready to describe some other settings like `STREAMING_PARALLELISM`. @yezizip2012 What do you think? 

- **Notes**

  [ Include any supplementary context or references here. ]

- **Related code PR**

  [ Provide a link to the relevant code PR here, if applicable. ]

- **Related doc issue**
  
  Resolves #1036

## For reviewers

- **Preview**

  [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **upcoming** version of the documentation. ]

- **Key points**

  [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Comment by yezizp2012** [comment]
Yes, we don't have a default value for `datastyle`, so it's acceptable for me to not include it for now. 
And for `STREAMING_PARALLELISM`, I think it's okay to include it but might need some explanation for it: if `STREAMING_PARALLELISM` is non-zero, all commands in this session of creating streaming jobs will use it as streaming parallelism.

**Comment by hengm3467** [comment]
I see. Shall we review all parameters and see which ones to describe? cc @neverchanje

image

**Comment by neverchanje** [comment]
I agree that we need descriptions somewhere for these settings. But in order to reduce our efforts, I suggest documenting them through `pg_settings` https://www.postgresql.org/docs/current/view-pg-settings.html, which is the system table for all settings. @yezizp2012 There is a column named 'short_desc' that will provide users their meaning.

Screenshot 2023-07-18 at 16 08 03

https://crate.io/docs/crate/reference/en/5.3/config/session.html CrateDB indeeds maintain a doc. But not all databases did the same.

**Review by emile-00 — APPROVED** [review]

**Comment by hengm3467** [comment]
Let's decouple the description of messages and the `current_setting()` function. In this doc PR, let's just list the settings. 

@yezizip2012 FYI. I created some descriptions of the settings, but think it might make more sense to include them in https://github.com/risingwavelabs/risingwave/issues/11014 . Here are the descriptions:

|`server_version`|PostgreSQL server version. |
|`server_version_num`| PostgreSQL server version, in the numeric format. Version `8.3.0` will be displayed as `80300` in the numeric format.|
|`timezone`|Timezone for the current instance. |
|`query_mode`| Query mode of RisingWave. Enum values: `auto`, `batch`, `streaming`. The default value is `auto`.|
|`streaming_parallelism`| The number of actors assigned to each streaming job. If it is set to non-zero, all streaming jobs in the current session will use it as the parallelism setting. |
|`batch_parallelism`| The number of actors assigned to each streaming job. If it is set to non-zero, all streaming jobs in the current session will use it as the parallelism setting.|

**Pull request merged**
