### PR TITLE
fix: move schema registry related options into format encode parts

### PR DESCRIPTION
**Pull request by tabVersion**
## Info

- **Description**

  - [ What's changed? Which parts of the docs are affected? ]
  - Move `schema.registry.username` and `schema.registry.password` into `format_encode_options`, the doc part is not consistent with code impl
  - `schema_registry_url` have been renamed to `schema.registry`

Not sure why this part of config is Italic type, still follow the practice. 

- **Notes**

  - [ Include any supplementary context or references here. ]

- **Related code PR**

  - [ Provide a link to the relevant code PR here, if applicable. ]

- **Related doc issue**
  
  Resolves [ Provide a link to the relevant doc issue here, if applicable. ]

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Review by Rossil2012 — APPROVED** [review]
LGTM.

**Comment by hengm3467** [comment]
@tabVersion @CharlieSYH  I think we'll need to duplicate the change in the 'docs' folder (that is, v1.5 docs)?

**Review by hengm3467 — APPROVED** [review]
LGTM. Thanks.

**Review by CharlieSYH — APPROVED** [review]
LGTM

**Pull request merged**
