### PR TITLE
Document EXCEPT clause for SELECT statement

### LINKED ISSUE #1034: Document EXCEPT clause for SELECT statement
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10438

syntax change: https://github.com/risingwavelabs/risingwave/pull/10723

### Which part(s) of the docs might be affected or should be updated? And how?

Document EXCEPT clause for SELECT statement

### Reference

_No response_

### PR DESCRIPTION
**Pull request by CharlieSYH**
## Info

- **Description**

  [ What's changed? Which parts of the docs are affected? ]

- **Notes**

  [ Include any supplementary context or references here. ]

- **Related code PR**

  https://github.com/risingwavelabs/risingwave/pull/10438

  https://github.com/risingwavelabs/risingwave/pull/10723

- **Related doc issue**
  
  Resolves https://github.com/risingwavelabs/risingwave-docs/issues/1034

## For reviewers

- **Preview**

  [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **upcoming** version of the documentation. ]

- **Key points**

  [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Comment by wugouzi** [comment]
We could wait for the approval of [this pr](https://github.com/risingwavelabs/risingwave/pull/10723) since it changes the syntax a little bit.

**Comment by CharlieSYH** [comment]
> We could wait for the approval of [this pr](https://github.com/risingwavelabs/risingwave/pull/10723) since it changes the syntax a little bit.

@wugouzi We can consider introducing the EXCEPT clause in the next release. Since it is not finalized in version 1.0, we shouldn't show it to users.

**Comment by wugouzi** [comment]
Agree, since related sqlsmith tests haven't been added too.

**Comment by CharlieSYH** [comment]
Closing this PR since this feature is not ready yet.

**Comment by hengm3467** [comment]
I see the feature PR was merged, so I'm reopening this PR.

**Comment by hengm3467** [comment]
@wugouzi Please help review the updates in this PR. Thanks!

**Comment by wugouzi** [comment]
Current syntax is 
```
select [table name.]* except ([column names])
```
For example, `select a.* except (a.id) from a, b`.

**Review by wugouzi — APPROVED** [review]

**Pull request merged**
