### PR TITLE
Add diagram to CREATE VIEW

### PR DESCRIPTION
**Pull request by bernscode**
Add diagram to CREATE VIEW.

## Info
- **Description**: 
Add diagram to CREATE VIEW.

- **Preview**: 
https://pr-616.d2fbku9n2b6wde.amplifyapp.com/docs/upcoming/sql-create-view/

- **Related code PR**: 
N/A

- **Related doc issue**: 
Resolves no doc issue.

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: image
</details>

### CODE REVIEW

**Comment by hengm3467** [comment]
@bernscode Here is my version: 
image


The code is like this: 
```
import rr from '@theme/RailroadDiagram'

export const svg = rr.Diagram(
   rr.Stack(
      rr.Sequence(
         rr.Terminal('CREATE USER'),
         rr.NonTerminal('source_name'), 
         rr.Optional('WITH', 'skip'),
         rr.ZeroOrMore('option',',', 'skip'),
      ),
      ),
         rr.Terminal(';'),
);

<drawer SVG={svg} />
```

You may want to check the containers section on this page:

https://pypi.org/project/railroad-diagrams/

**Comment by hengm3467** [comment]
@bernscode This command doesn't use space as the delimiter, but instead comma. Instead of using a rr.Commment, you must want to use `','` instead.

**Comment by bernscode** [comment]
@hengm3467 Thanks for the clarification. I've made the update in the latest commit. Thanks!

**Review by hengm3467 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
