### PR TITLE
Update generate_series example to use `NOW()::timestamp` since timestamptz is not supported for generate_series

### PR DESCRIPTION
**Pull request by kwannoel**
## Description

generate_series only works with timestamp, not timestamptz. The example in our doc fails due to this. Perhaps some regression? Not sure if `NOW()` changed to return `timestamptz` instead of `timestamp`.

```
dev=> create materialized view m1 as SELECT time::timestamptz FROM generate_series(
  '2020-01-01 00:00:00',
  now(),
  interval '1 hour'
) t(time);
ERROR:  Failed to run the query

Caused by:
  function generate_series(unknown, timestamp with time zone, interval) does not exist


dev=> create materialized view m1 as SELECT * FROM generate_series(
  '2020-01-01 00:00:00'::timestamptz,
  now(),
  interval '1 hour'
);
NOTICE:  Your session timezone is UTC. It was used in the interpretation of timestamps and dates in your query. If this is unintended, change your timezone to match that of your data's with `set timezone = [timezone]` or rewrite your query with an explicit timezone conversion, e.g. with `AT TIME ZONE`.

CREATE_MATERIALIZED_VIEW
```

## Related doc issue

Resolve

## Checklist

- [ ] I have checked the doc site preview, and the updated parts look good.
- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`emile-00`, `hengm3467`, & `WanYixian`).

### CODE REVIEW

**Comment by stdrc** [comment]
Streaming `generate_series` with `now()` as end doesn't go through the normal function binding path. The example in doc is streaming query, not batch query, though this is indeed a bit confusing.

**Comment by kwannoel** [comment]
> Streaming `generate_series` with `now()` as end doesn't go through the normal function binding path. The example in doc is streaming query, not batch query, though this is indeed a bit confusing.


```
dev=> create materialized view m1 as SELECT time::timestamptz FROM generate_series(
  '2020-01-01 00:00:00',
  now(),
  interval '1 hour'
) t(time);
ERROR:  Failed to run the query

Caused by:
  function generate_series(unknown, timestamp with time zone, interval) does not exist

```

Is it a regression then? 🤔

**Comment by stdrc** [comment]
> > Streaming `generate_series` with `now()` as end doesn't go through the normal function binding path. The example in doc is streaming query, not batch query, though this is indeed a bit confusing.
> 
> ```
> dev=> create materialized view m1 as SELECT time::timestamptz FROM generate_series(
>   '2020-01-01 00:00:00',
>   now(),
>   interval '1 hour'
> ) t(time);
> ERROR:  Failed to run the query
> 
> Caused by:
>   function generate_series(unknown, timestamp with time zone, interval) does not exist
> ```
> 
> Is it a regression then? 🤔

Interesting... Let me fix this tmr🤣

**Comment by kwannoel** [comment]
> > > Streaming `generate_series` with `now()` as end doesn't go through the normal function binding path. The example in doc is streaming query, not batch query, though this is indeed a bit confusing.
> > 
> > 
> > ```
> > dev=> create materialized view m1 as SELECT time::timestamptz FROM generate_series(
> >   '2020-01-01 00:00:00',
> >   now(),
> >   interval '1 hour'
> > ) t(time);
> > ERROR:  Failed to run the query
> > 
> > Caused by:
> >   function generate_series(unknown, timestamp with time zone, interval) does not exist
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it a regression then? 🤔
> 
> Interesting... Let me fix this tmr🤣

Okay no rush, you can take a look first. I updated the doc accoridngly. Thanks for clarifying it's in streaming, I missed that part.

**Review by stdrc — APPROVED** [review]

**Review by WanYixian — APPROVED** [review]

**Pull request merged**
