### PR TITLE
speed up ci

### PR DESCRIPTION
**Pull request by xxchan**
## Info

- **Description**

  [ What's changed? Which parts of the docs are affected? ]

- **Notes**

  [ Include any supplementary context or references here. ]

- **Related code PR**

  [ Provide a link to the relevant code PR here, if applicable. ]

- **Related doc issue**
  
  Resolves [ Provide a link to the relevant doc issue here, if applicable. ]

## For reviewers

- **Preview**

  [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **upcoming** version of the documentation. ]

- **Key points**

  [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Comment by xxchan** [comment]
before 1m + 6m46s
image

after 20s + 4m

**Review by Ad-Bean — APPROVED** [review]
LGTM! but why no minify can speed up the build, I wonder if it can also be used on Amplify.

**Comment by xxchan** [comment]
Guess it's a tradeoff between compilation time and build target size/speed, like debug build vs release build. For production, it's still better to minify.

**Comment by CharlieSYH** [comment]
Thanks a lot, @xxchan!

**Pull request merged**
