### PR TITLE
Replace NOW() with PROCTIME()

### LINKED ISSUE #803: replace now() with proctime() in temporal filters
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9144

### Which part(s) of the docs might be affected or should be updated? And how?

SQL patterns -> Temporal filters.
As we already documented proctime() in a separate PR (#788). We now only need to replace the now() function with the proctime() function.

### Reference

_No response_

### PR DESCRIPTION
**Pull request by bernscode**
Replace NOW() with PROCTIME().

## Info
- **Description**: 
Replace NOW() with PROCTIME().

- **Preview**: 
https://pr-817.d2fbku9n2b6wde.amplifyapp.com/docs/upcoming/sql-pattern-temporal-filters/

- **Related code PR**: 
https://github.com/risingwavelabs/risingwave/pull/9144

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/803

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: image
</details>

### CODE REVIEW

**Comment by chenzl25** [comment]
This PR https://github.com/risingwavelabs/risingwave/pull/9144 is trying to replace `NOW()` with `PROCTIME()` for the temporal join but not the temporal filter. They are different. @yuhao-su Will `PROCTIME()` be used for temporal filtering?

**Comment by hengm3467** [comment]
> This PR [risingwavelabs/risingwave#9144](https://github.com/risingwavelabs/risingwave/pull/9144) is trying to replace `NOW()` with `PROCTIME()` for the temporal join but not the temporal filter. They are different. @yuhao-su Will `PROCTIME()` be used for temporal filtering?

Thanks for identifying this gap. @yuhao-su Could you please help confirm? Thanks.

**Comment by hengm3467** [comment]
@bernscode Just confirmed with @yuhao-su: For temporal fitlers, people should use now() instead of proctime(). Otherwise, it will become a normal filter. 
That means that we need to close this PR, and re-open a doc issue.

**Comment by hengm3467** [comment]
Closing this one as the issue is reopened in #https://github.com/risingwavelabs/risingwave-docs/issues/860

**Pull request closed without merging**
