### PR TITLE
feat(docs): Ingest from kafka

### PR DESCRIPTION
**Pull request by CAJan93**
## Info

- **Description**

- Quick description telling users how they can get infos about the internal columns of a kafka source. 

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Comment by fuyufjh** [comment]
Hmmm, this is misleading...

`_rw_kafka_timestamp` was already documented at https://docs.risingwave.com/docs/dev/ingest-from-kafka/#query-kafka-timestamp

`_row_id` is not only for Kafka but for all kinds of Sources. We didn't document it because we thought the columns should never be used by users directly. It's okay to document it, but I didn't find a good place for it.

**Comment by CAJan93** [comment]
> It's okay to document it, but I didn't find a good place for it

Do you have a suggestion where to document it? How about here https://github.com/risingwavelabs/risingwave-docs/blob/main/docs/sql/commands/sql-describe.md ?

**Comment by hengm3467** [comment]
@CAJan93 I'm curious about when `_row_id` will be used. If there is some trick that is applicable to all sources, then we can document this in the overview of ingesting data.

**Comment by CAJan93** [comment]
> I'm curious about when _row_id will be used. 

This is a question for @st1page 😁 I have not looked at the code, but AFAIK `_row_id` is generated by RW not Kafka and it is the primary ID by default, so I guess it is just a counter?

**Comment by st1page** [comment]
> > I'm curious about when _row_id will be used.
> 
> This is a question for @st1page 😁 I have not looked at the code, but AFAIK `_row_id` is generated by RW not Kafka and it is the primary ID by default, so I guess it is just a counter?

For batch query, `SELECT _row_id FROM source` will generated a NULL value.
For Streaming query, such as `CREATE MATERIALIZED VIEW AS SELECT _row_id FROM source`, RW will add a row id generator  after the source data's ingestion with a snowflake-like algorithm(https://en.wikipedia.org/wiki/Snowflake_ID) which can assign a unique id for each record.

**Comment by fuyufjh** [comment]
These part has been heavily refactored. Continue on #1750

**Pull request closed without merging**
