### PR TITLE
Add SET TIME ZONE

### LINKED ISSUE #665: Document SET TIME ZONE
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/8572

### Which part(s) of the docs might be affected or should be updated? And how?

Document this new SQL statement, including its syntax and examples.

The basic syntax is:
`SET [ SESSION | LOCAL ] TIME ZONE { value | 'value' | LOCAL | DEFAULT }`

Please find out what values are supported from @TennyZhuang . 

### Reference

https://it-inzhener.com/en/articles/detail/postgresql-set-timezone

### PR DESCRIPTION
**Pull request by bernscode**
Add SET TIME ZONE.

## Info
- **Description**: 
Add SET TIME ZONE.

- **Preview**: 
[ Paste the preview link to the edited page here. ]

- **Related code PR**: 
https://github.com/risingwavelabs/risingwave/pull/8572

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/665

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: image
</details>

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]

**Comment by hengm3467** [comment]
@tennyzhuang I'm wondering where we can find all the allowed values for time zones? We can point users to a place having such values.

**Comment by TennyZhuang** [comment]
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by bernscode** [comment]
@hengm3467 Great point! Thanks @TennyZhuang! I've added the link in the time_zone description and also added the diagram in the latest commit.

**Review by hengm3467 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
