### PR TITLE
RunLLM Search Widget Configuration

### PR DESCRIPTION
**Pull request by agiron123**
## Info

- **Description**

  This PR adds the RunLLM Search Widget to the Rising Wave Docs

- **Related code PR**

  - [ Provide a link to the relevant code PR here, if applicable. ]

- **Related doc issue**
  
  Resolves [ Provide a link to the relevant doc issue here, if applicable. ]

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

### CODE REVIEW

**Comment by hengm3467** [comment]
The new widget works well for me,  but I find the old widget is still there. @TingJianZheng @luotianchun  Please help remove the old AI widget. Thanks!

**Comment by agiron123** [comment]
> The new widget works well for me, but I find the old widget is still there. @TingJianZheng @luotianchun Please help remove the old AI widget. Thanks!

@hengm3467 Glad to hear that the new widget works well. Let me know if you have any questions or feedback. 

As is, merging this PR would result in the two widgets being on top of each other, so I recommend first taking care of the work to remove the current widget and then merging this PR. 

Happy to help remove the existing widget, just let me know and I can get a PR up.

**Comment by hengm3467** [comment]
> > The new widget works well for me, but I find the old widget is still there. @TingJianZheng @luotianchun Please help remove the old AI widget. Thanks!
> 
> @hengm3467 Glad to hear that the new widget works well. Let me know if you have any questions or feedback.
> 
> As is, merging this PR would result in the two widgets being on top of each other, so I recommend first taking care of the work to remove the current widget and then merging this PR.
> 
> Happy to help remove the existing widget, just let me know and I can get a PR up.

@agiron123 Thanks for the notes. The old widget was just removed in #2067 , so I think we are good to merge this PR.

**Review by hengm3467 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
